- name: Set Server Name
  ansible.builtin.set_fact:
    server_name: "{{ os_default_prefix }}{{ item.name }}"

- name: "Get Info of '{{ item.name }}' instance"
  openstack.cloud.server_info:
    auth: "{{ os_auth }}"
    name: "{{ server_name }}"
  register: info_response
  failed_when: false

- name: Set Default for ssh username
  ansible.builtin.set_fact:
    _default_ssh_username: "{{ username.value }}"
  loop: "{{ lookup('ansible.builtin.dict', default_ssh_username) }}"
  loop_control:
    loop_var: username
    label: "{{ username.key }}"
  when: username.key in item.image_name

- name: "Create molecule instance '{{ item.name }}'"
  when: info_response.servers | length == 0
  openstack.cloud.server:
    auth: "{{ os_auth }}"
    state: present
    auto_ip: false
    wait: true
    name: "{{ server_name }}"
    image: "{{ item.image_name }}"
    flavor: "{{ item.flavor | default(os_default_flavor_name) }}"
    security_groups:
      - default
    key_name: "{{ os_key_pair_name }}"
    network: "{{ item.network | default(os_default_int_network_name) }}"
    floating_ip_pools: "{{ item.fip_pool | default(omit) }}"
    meta:
      instance: "{{ item.name }}"
      ssh_user: "{{ item.ssh_user | default(_default_ssh_username) }}"
      owner: "{{ os_username | default('') }}"
      ansible_role: "{{ galaxy_info[1:] | default('') }}"
  register: server
  async: 7200
  poll: 0
