- name: "Get Info of '{{ item.name }}' instance"
  openstack.cloud.server_info:
    auth: "{{ os_auth }}"
    name: "{{ item.name }}"
  register: info_response
  failed_when: false

- name: "Create molecule instance '{{ item.name }}'"
  when: info_response.servers | length == 0
  openstack.cloud.server:
    auth: "{{ os_auth }}"
    state: present
    auto_ip: true
    wait: true
    name: "{{ os_default_prefix }}{{ item.name }}"
    image: "{{ item.image_name }}"
    flavor: "{{ item.flavor | default(os_default_flavor_name) }}"
    security_groups:
      - default
    key_name: "{{ os_key_pair_name }}"
    network: "{{ item.network | default(os_default_int_network_name) }}"
    floating_ip_pools: "{{ item.fip_pool | default(omit) }}"
    meta:
      instance: "{{ item.name }}"
      ssh_user: "{{ item.ssh_user | default(default_ssh_username[item.image_name]) }}"
      owner: "{{ os_username | default('') }}"
      ansible_role: "{{ galaxy_info[1:] | default('') }}"
  register: server
  async: 45
  poll: 0
