---
- name: Assert env vars
  ansible.builtin.include_tasks: helper/assert.yml

- name: Get galaxy info-based prefix
  ansible.builtin.include_tasks: helper/lookup_galaxy_info.yml

- name: Create network
  openstack.cloud.network:
    auth: "{{ os_auth }}"
    name: "{{ os_default_int_network_name }}"
    state: present
    external: "false"
  register: create_network_response
  retries: 5
  until: create_network_response.failed == false

- name: Create subnet in network
  openstack.cloud.subnet:
    auth: "{{ os_auth }}"
    name: "{{ os_default_int_subnet_name }}"
    state: present
    network_name: "{{ os_default_int_network_name }}"
    cidr: "{{ os_default_int_subnet_cidr }}"
    ip_version: 4
    dns_nameservers: 8.8.8.8
#    host_routes: "{{ item.network.subnet.host_routes | default(omit) }}"
#  loop: "{{ molecule_yml.platforms }}"

- name: Create Router
  openstack.cloud.router:
    auth: "{{ os_auth }}"
    name: "{{ os_default_router_name }}"
    state: present
    network: "{{ os_default_network_name }}"
    interfaces:
      - net: "{{ os_default_int_network_name }}"
        subnet: "{{ os_default_int_subnet_name }}"

- name: Create local ssh key pair
  ansible.builtin.include_tasks: helper/create_local_key_pair.yml

- name: Create openstack key pair
  openstack.cloud.keypair:
    auth: "{{ os_auth }}"
    name: "{{ os_key_pair_name }}"
    public_key_file: "{{local_key_pair_path}}{{ local_key_pair_file }}.pub"
  register: key_pair_response

- ansible.builtin.debug:
    var: molecule_yml.platforms | flatten(levels=1)

- name: Create molecule instance(s)
  ansible.builtin.include_tasks: helper/create_instance.yml
  loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"

- name: Wait till all instance info are available
  ansible.builtin.include_tasks: helper/wait_till_instance_info_avail.yml
  loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"

- name: Collect instance info
  openstack.cloud.server_info:
    auth: "{{ os_auth }}"
    name: "{{ os_default_prefix }}{{ item.name }}"
  loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"
  register: instance_info

- name: Attach floating IP to instance
  loop: "{{ instance_info.results }}"
  ansible.builtin.include_tasks: helper/attach_floating_ip.yml

- name: Collect instance info
  openstack.cloud.server_info:
    auth: "{{ os_auth }}"
    name: "{{ os_default_prefix }}{{ item.name }}"
  loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"
  register: instance_info

- name: Flatten instance_info
  ansible.builtin.set_fact:
    server_info: "{{ server_info | default([]) + item.servers }}"
  loop: "{{ instance_info.results }}"

# Mandatory configuration for Molecule to function.
- name: Populate instance config dict
  ansible.builtin.set_fact:
    instance_conf_dict: {
      'instance': "{{ item.metadata.instance }}",
      'instance_id': "{{ item.id }}",
      'address': "{{ item.access_ipv4 }}",
      'user': "{{ item.metadata.ssh_user }}",
      'port': "{{ item.ssh_port | default(default_ssh_port) }}",
      'identity_file': "{{ local_key_pair_path }}{{ local_key_pair_file }}", }
  loop: "{{ server_info }}"
  register: instance_config_dict

- name: Convert instance config dict to a list
  ansible.builtin.set_fact:
    instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

- name: Dump instance config
  ansible.builtin.copy:
    content: "{{ instance_conf | to_json | from_json | to_yaml }}"
    dest: "{{ molecule_instance_config }}"

- name: Wait till ssh port available
  ansible.builtin.wait_for:
    host: "{{ item.access_ipv4 }}"
    port: "{{ item.ssh_port | default(default_ssh_port) }}"
    timeout: 300
  loop: "{{ server_info }}"
