---
# molecule_instance_config might not be present, therefore ignore errors and default to an empty config
- name: List of instances to be deleted
  ansible.builtin.debug:
    var: lookup('file', molecule_instance_config, errors='ignore') | default([], true) | from_yaml | flatten(levels=1)

- name: Destroy molecule instance(s)
  ansible.builtin.shell: 
    cmd: >
      openstack server delete --wait {{ item.instance_id }}
  environment:
    OS_PROJECT_NAME: "{{ os_auth.project_name }}"
    OS_DOMAIN_NAME: "{{ os_auth.domain_name }}"
  loop: "{{ lookup('file', molecule_instance_config, errors='ignore') | default([], true) | from_yaml | flatten(levels=1) }}"
  register: delete_instance_response
  retries: 10
  failed_when: 
    - delete_instance_response.rc != 0
    - '"No Server found" not in delete_instance_response.stderr'
  until: delete_instance_response.rc == 0

- name: Create local ssh key pair
  ansible.builtin.include_tasks: helper/create_local_key_pair.yml

- name: Delete keypair
  openstack.cloud.keypair:
    auth: "{{ os_auth }}"
    name: "{{ os_key_pair_name }}"
    state: absent
  register: delete_keypair_response
  retries: 5
  until: delete_keypair_response.failed == false

# Mandatory configuration for Molecule to function.
- name: Populate instance config
  ansible.builtin.set_fact:
    instance_conf: {}

- name: Dump instance config
  ansible.builtin.copy:
    content: "{{ instance_conf | to_json | from_json | to_yaml }}"
    dest: "{{ molecule_instance_config }}"
  # when: server.changed | bool
