---
# molecule_instance_config might not be present, therefore ignore errors and default to an empty config
- name: List of instances to be deleted
  debug:
    var: lookup('file', molecule_instance_config, errors='ignore') | default([], true) | from_yaml | flatten(levels=1)

- name: Destroy molecule instance(s)
  openstack.cloud.server:
    auth: "{{ os_auth }}"
    name: "{{ item.instance_id }}"
    state: absent
    delete_fip: true
  register: server
  loop: "{{ lookup('file', molecule_instance_config, errors='ignore') | default([], true) | from_yaml | flatten(levels=1) }}"
  async: 7200
  poll: 0

- name: Wait for instance(s) deletion to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: os_jobs
  until: os_jobs.finished
  retries: 300
  loop: "{{ server.results | flatten(levels=1) }}"

- name: Create local ssh key pair
  ansible.builtin.include_tasks: helper/create_local_key_pair.yml

- name: Delete keypair
  openstack.cloud.keypair:
    auth: "{{ os_auth }}"
    name: "{{ os_key_pair_name }}"
    state: absent
  register: delete_keypair_response
  retries: 5
  until: delete_keypair_response.failed == false

# Mandatory configuration for Molecule to function.
- name: Populate instance config
  set_fact:
    instance_conf: {}

- name: Dump instance config
  copy:
    content: "{{ instance_conf | to_json | from_json | to_yaml }}"
    dest: "{{ molecule_instance_config }}"
  when: server.changed | bool
