---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: centos8
    image_name: CentOS 8 64-bit
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
