---
dependency:
  name: galaxy
driver:
  name: default
platforms:
# UBUNTU
  - name: ubuntu1804
    image_name: Ubuntu 18.04 64-bit
    groups: ['ssh']

  - name: ubuntu2004
    image_name: Ubuntu 20.04 64-bit
    groups: ['ssh']

  - name: ubuntu2204
    image_name: Ubuntu 22.04 64-bit
    groups: ['ssh']

  - name: ubuntu2404
    image_name: Ubuntu 24.04 64-bit
    groups: ['ssh']

## CENTOS
  - name: centos7
    image_name: CentOS 7 64-bit
    groups: ['ssh']

  - name: centos8
    image_name: CentOS 8 64-bit
    groups: ['ssh']

  - name: centos9
    image_name: CentOS 9 Stream 64-bit
    groups: ['ssh']

  - name: centos10
    image_name: CentOS 10 Stream 64-bit
    groups: ['ssh']

# DEBIAN
  - name: debian11
    image_name: Debian 11 64-bit
    groups: ['ssh']

  - name: debian12
    image_name: Debian 12 64-bit
    groups: ['ssh']

  - name: debian13
    image_name: Debian 13 64-bit
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
