---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ubuntu1804
    image_name: Ubuntu 18.04 64-bit (Ansible)
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
